### ISSUE TITLE
add common-service dependency layer

### ISSUE THREAD

**Issue by gclayburg** [gclayburg/dockerPreparePlugin#2]
From:
https://github.com/Transmode/gradle-docker/issues/64
@liqweed

I have a code base with multiple projects, some of them are Spring Boot services. Each project has it's own unique dependencies but all share a common dependency on a 'common-service' project which in turn depends on Spring Boot etc. It would be great if there was a Docker layer for this 'common-service' (including common 3rd parties that don't change that often), a layer for the unique dependencies of each Spring Boot project and then a layer for the project's jar. I'm deploying on-prem so this could reduce the overall size considerably.

**Comment by gclayburg** [comment]
I'm thinking of adding a build.gradle setting that might look like this:

```
dockerprepare {
  commonService 'spring-boot-starter-web'
}
```

spring-boot-starter-web has 21 transitive dependencies.  During a build, all 21 resolved jar files would be copied into the first layer, giving us 3 layers:

L1: spring-boot-starter-web 
L2: all other dependent jar files
L3: everything else, i.e. src/main/**

**Comment by liqweed** [comment]
That would be an awesome feature.

If the commonService could be configured to be a project dependency that would essentially allow to tuck away in L1 layer many other 3rd parties (we have protobuf/gRPC, vavr, Guava, resilience4j and Ignite to name a few). Multi-project Gradle configuration would definitely benefit from that.

One could make the case that looking at inter-project dependencies, the dependency tree (just between the different projects) outlines the optimal reusable layer structure.

**Comment by gclayburg** [comment]
ok, This is implemented now.  I changed the syntax a little to allow for multiple dependencies in the commonService layer:

```
dockerprepare{
    commonService ['org.springframework.boot:spring-boot-starter-web','org.springframework.boot:spring-boot-starter-actuator']
}
```

**Comment by gclayburg** [comment]
fixed in this version:

plugins {
  id "com.garyclayburg.dockerprepare" version "1.1.0"
}

**Comment by liqweed** [comment]
Works perfectly, thank you!
